version: '3'
services:
  mysql:
    container_name: docker-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "33060:3306"
    restart: always
  web:
    container_name: docker-php
    build: .
    environment:
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
    ports:
      - "8080:80"
      - "3000:3000"
    volumes:
      - .:/var/www/html
    restart: always